### PR TITLE
Fix to allow library to work with Python3

### PR DESCRIPTION
**Pull request by tanabi**

### CODE REVIEW

**Comment by jonafato** [comment]
Any update here? Would be great to use this on Python 3.

**Comment by tanabi** [comment]
This hasn't been updated in years, so I don't know if the original programmer is actually maintaining it anymore :)

**Comment by jonafato** [comment]
That's unfortunate. I'd be happy to help maintain the library if @seme0021 is interested.

**Comment by seme0021** [comment]
Sorry, have not been getting notifications for this project!

**Pull request merged**
